### ISSUE TITLE
"invalid player data" when using custom configs.

### ISSUE THREAD

**Issue by adrizzyglizzy** [henkelmax/delivery-questing#5]
**Bug description**
The problem is that the game fails to join a world because of "invalid player data" and the reason is the id that is prompted in the "task.json" file when trying to make custom tasks. Offers work just fine it is just the tasks that don't work. I have tried running the mod in a custom modpack and in an environment where only this mod and its dependencies are featured. I have tried different UUIDs and even used the same id which can be found in the "Delivery, inc" modpack. 

**Steps to reproduce the issue**
1. create a delivery config directory and insert the skins folder from the "delivery, inc" mod pack.
2. create a task.json file in *\config\delivery and insert the task which follows the same structure as in the "delivery, inc" mod pack.
3. add any UUID in the "id"  field

**Expected behavior**
I expect the mod to function as intended where the player can enter a world and play through the different custom tasks made in the config folder.

**Log files**
here is the extract from the log where the error occurred: [https://pastebin.com/4TwdPghP](url)

**Versions**
- MC version: 1.18.2
- Forge version: 40.2.0
- Mod version: 1.1.1

**Other mods**
This issue has been replicated in an environment with no additional mods except for the "camera mod-1.18.2-1.0.5" and "patchouli-1.18.2-71.1"

**Screenshots (Optional)**
**note**: this issue occurs in both single- and multiplayer.
![image](https://user-images.githubusercontent.com/126838591/222612054-bbfdb704-1b7d-4a75-821a-c1a2151abda1.png)

**Comment by merdink** [comment]
@TheObnoxiousPig I had the same issue until I looked at the logs and realized it was looking for "endgameTasks" in the tasks.json.

Did you include that in your tasks file?

Silly me, just checked the log you posted.
`java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.endgameTasks" is null`
I had the same error, just make sure there is an endgameTasks section in your tasks file and that should fix it.
